package com.poultryflow.audit;

public enum AuditAction {
    FARM_PROFILE_CREATED,
    FARM_PROFILE_UPDATED,
    FARM_MEMBERSHIP_OWNER_BOOTSTRAPPED,
    FARM_MEMBERSHIP_INVITED,
    FARM_MEMBERSHIP_INVITATION_CLAIMED,
    FARM_MEMBERSHIP_ROLES_CHANGED,
    FARM_MEMBERSHIP_DISABLED,
    FARM_MEMBERSHIP_RE_ENABLED,
    FARM_LOCATION_CREATED,
    FARM_LOCATION_UPDATED,
    FARM_LOCATION_ACTIVATED,
    FARM_LOCATION_DEACTIVATED
}
