spring.application.name=PoultryFlow

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${POULTRYFLOW_OIDC_ISSUER_URI:http://localhost:8081/realms/poultryflow}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${POULTRYFLOW_OIDC_JWK_SET_URI:http://localhost:8081/realms/poultryflow/protocol/openid-connect/certs}
spring.security.oauth2.resourceserver.jwt.audiences=${POULTRYFLOW_OIDC_AUDIENCE:poultryflow-api}
