spring.application.name=PoultryFlow

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
